[unstable]
# build-std = ["core", "compiler_builtins", "alloc", "std"]
# build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-coral-unknown-kernel"

[target.'cfg(target_vendor = "coral")']
runner = "bootimage runner"
