[package]
name = "coral-collections"
version = "0.1.0"
edition = "2021"

[dependencies]
cranelift-entity = { git = "https://github.com/CharlyCst/wasmtime.git", branch = "restricted-std" }
hashbrown = "0.9.1"
