[workspace]
resolver = '2'
members = [
    # The kernel itself
    "kernel",

    # Userspace programs
    "userland/userboot",

    # Dependencies
    "crates/collections",
    "crates/compiler",
    "crates/wasm",
    "crates/bindgen"
]
