[package]
name = "kranelift"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Cranelift Dependencies
cranelift-wasm = "0.80.0"
cranelift-codegen = "0.80.0"
cranelift-entity = "0.80.0"
