[package]
name = "coral-bindgen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cold"
path = "src/main.rs"

[dependencies]
walrus = "0.19.0"
anyhow = "1.0"
clap = { version = "3.2.15", features = ["derive"] }

