[tables.coral]
from = "coral"
name = "handles"
min_size = 2
max_size = 4

[tables.module]
min_size = 4

[functions.vma_write]
from = "coral"
patches = [
    { arg = 0, table = "module" },
    { arg = 1, table = "coral" },
]

